name: Custom Jellyfin Image with GA

on:
  workflow_dispatch:
    inputs:
      JELLYFIN_RELEASE:
        description: 'JELLYFIN RELEASE'
        required: true
        default: '10.9.9'
        type: choice
        options:
          - 10.9.9
          - 10.9.10
          - 10.9.11


jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: BuildLatestDockerImage
        run: docker build  . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/jellyfin:latest
      - name: BuildSelectDockerImage
        run: docker build --build-arg JELLYFIN_RELEASE=${{ inputs.JELLYFIN_RELEASE }} . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/jellyfin:${{ inputs.JELLYFIN_RELEASE }}
      - name: Publish Latest to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/jellyfin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
      - name: Publish Select to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          JELLYFIN_RELEASE: ${{inputs.JELLYFIN_RELEASE}}
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/jellyfin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: JELLYFIN_RELEASE
          tags: ${{inputs.JELLYFIN_RELEASE}}
