name: Custom Jellyfin Image with GA

on:
  workflow_dispatch:
    inputs:
      JELLYFIN_RELEASE:
        description: 'JELLYFIN RELEASE'
        required: true
        default: '10.8.8'
        type: choice
        options:
          - 10.8.1
          - 10.8.2
          - 10.8.3
          - 10.8.4
          - 10.8.5
          - 10.8.6
          - 10.8.7
          - 10.8.8
      FFMPEG5_RELEASE:
        description: 'JELLYFIN_FFMPEG5 RELEASE'
        required: true
        default: '5.1.2-4'
        type: choice
        options:
          - 5.1.2-1
          - 5.1.2-2
          - 5.1.2-3
          - 5.1.2-4
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: BuildLatestDockerImage
        run: docker build  . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/jellyfin:latest
      - name: BuildSelectDockerImage
        run: docker build --build-arg JELLYFIN_RELEASE=${{ inputs.JELLYFIN_RELEASE }} FFMPEG5_RELEASE=${{inputs.FFMPEG5_RELEASE}} . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/jellyfin:${{ inputs.JELLYFIN_RELEASE }}
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/jellyfin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ inputs.JELLYFIN_RELEASE }}"
